version: "3.4"

services:
  mattermost-app:
    image: eugenmayer/mattermost-app:team-${VERSION}
    environment:
      MM_USERNAME: ${MATTERMOST_DB_USER}
      MM_PASSWORD: ${MATTERMOST_DB_PASSWORD}
      MM_DBNAME: ${MATTERMOST_DB_NAME}
      MM_SERVICESETTINGS_SITEURL: ${MATTERMOST_URL}
      DB_HOST: mattermost-db
      DB_PORT_NUMBER: 5432
      # mandatory to fix the mattermost cli https://github.com/mattermost/mattermost-docker/issues/399#issuecomment-508991021
      MM_SQLSETTINGS_DATASOURCE: "postgres://${MATTERMOST_DB_USER}:${MATTERMOST_DB_PASSWORD}@mattermost-db:5432/${MATTERMOST_DB_NAME}?sslmode=disable&connect_timeout=10"
    volumes:
      - mattermost_config:/mattermost/config
      - mattermost_data:/mattermost/data
      - mattermost_logs:/mattermost/logs
      - mattermost_plugins:/mattermost/plugins
      - mattermost_client_plugins:/mattermost/client/plugins
    ports:
      - 8000:8000
  mattermost-db:
    image: eugenmayer/mattermost-db:team-${VERSION}
    volumes:
      - mattermost_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${MATTERMOST_DB_NAME}
      POSTGRES_USER: ${MATTERMOST_DB_USER}
      POSTGRES_PASSWORD: ${MATTERMOST_DB_PASSWORD}
      POSTGRES_ENCODING: "UNICODE"
      POSTGRES_COLLATE: "C"
      POSTGRES_COLLATE_TYPE: "C"

volumes:
  mattermost_config:
    driver: local
  mattermost_data:
    driver: local
  mattermost_logs:
    driver: local
  mattermost_plugins:
    driver: local
  mattermost_client_plugins:
    driver: local
  mattermost_db:
    driver: local
