version: "3.4"

services:
  mattermost-app:
    image: eugenmayer/mattermost-app:team-${VERSION}
    environment:
      MM_USERNAME: ${MATTERMOST_DB_USER}
      MM_PASSWORD: ${MATTERMOST_DB_PASSWORD}
      MM_DBNAME: ${MATTERMOST_DB_NAME}
      MM_SERVICESETTINGS_SITEURL: ${MATTERMOST_URL}
      DB_HOST: mattermost-db
      DB_PORT_NUMBER: 5432
      # mandatory to fix the mattermost cli https://github.com/mattermost/mattermost-docker/issues/399#issuecomment-508991021
      MM_SQLSETTINGS_DATASOURCE: "postgres://${MATTERMOST_DB_USER}:${MATTERMOST_DB_PASSWORD}@mattermost-db:5432/${MATTERMOST_DB_NAME}?sslmode=disable&connect_timeout=10"
    volumes:
      - ./data/mattermost/config:/mattermost/config
      - ./data/mattermost/data:/mattermost/data
      - ./data/mattermost/logs:/mattermost/logs
      - ./data/mattermost/plugins:/mattermost/plugins
      - ./data/mattermost/client_plugins:/mattermost/client/plugins
    ports:
      - ${MATTERMOST_PORT:-7007}:8000
    user: root
  mattermost-db:
    image: eugenmayer/mattermost-db:team-${VERSION}
    volumes:
      - ./data/mattermost/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${MATTERMOST_DB_NAME}
      POSTGRES_USER: ${MATTERMOST_DB_USER}
      POSTGRES_PASSWORD: ${MATTERMOST_DB_PASSWORD}
      POSTGRES_ENCODING: "UNICODE"
      POSTGRES_COLLATE: "C"
      POSTGRES_COLLATE_TYPE: "C"
