version: '3.4'

services:
  fusionauth-db:
    image: postgres:11.9-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${FUSIONAUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FUSIONAUTH_POSTGRES_PASSWORD}
    networks:
      - fusionauth-db
    restart: unless-stopped
    volumes:
      - ./data/fusionauth/db:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - fusionauth-db
    environment:
      DATABASE_URL: jdbc:postgresql://fusionauth-db:5432/fusionauth
      DATABASE_ROOT_USER: ${FUSIONAUTH_POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${FUSIONAUTH_POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${FUSIONAUTH_DATABASE_USER}
      DATABASE_PASSWORD: ${FUSIONAUTH_DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:${FUSIONAUTH_PORT:-7008}
      SEARCH_TYPE: database

    networks:
     - fusionauth-db
    restart: unless-stopped
    ports:
      - ${FUSIONAUTH_PORT:-7008}:9011
    volumes:
      - ./data/fusionauth/config:/usr/local/fusionauth/config

networks:
  fusionauth-db:
    driver: bridge
