version: '3.4'

services:
  sapper:
    image: fun-sapper
    build:
      context: ./
      dockerfile: ./docker/sapper/Dockerfile
      args:
      - DEPS_INSTALL=yarn
      - NODE_ENV=production
    volumes:
      - ./sapper:/app
      - ./data/sapper/npm:/root/.npm
      - /tmp/devday/sapper:/tmp
    restart: "always"
    environment:
      - NODE_ENV=production
      - GRAPHQL_ENDPOINT
      - VIRTUAL_HOST=sapper.local
      - LETSENCRYPT_HOST=sapper.local
    working_dir: /app
    command: ${SAPPER_COMMAND:-yarn start}
    ports:
      - ${SAPPER_PORT:-7006}:3000