version: "3.4"

 # See: https://github.com/nginx-proxy/nginx-proxy

services:
  nginx-proxy:
    # image: nginx:alpine

    # just like the usual nginx image, but brotli enabled
    image: fholzer/nginx-brotli
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      # we need to make it come later than "default" in the alphabetical order
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  nginx-dockergen:
    image: jwilder/docker-gen
    container_name: nginx-dockergen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
      - nginx-proxy-letsencrypt
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
      NGINX_DOCKER_GEN_CONTAINER: "nginx-proxy"
      DHPARAM_GENERATION: "false"
      DEFAULT_EMAIL: ${LETSENCRYPT_DEFAULT_EMAIL:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  static-website:

