version: '3.4'

services:
  matomo-db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - ./data/matomo/db:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=matomo
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MYSQL_ROOT_PASSWORD=matomo
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=matomo
      - MATOMO_DATABASE_DBNAME=matomo
    env_file:
      - ./docker/matomo/db.env

  matomo-app:
    image: matomo:fpm-alpine
    restart: always
    links:
      - matomo-db
    volumes:
#      - ./config:/var/www/html/config:rw
#      - ./logs:/var/www/html/logs
      - ./data/matomo/app:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=matomo-db
    env_file:
        - ./docker/matomo/db.env

  matomo-web:
    image: nginx:alpine
    restart: always
    environment:
      - MATOMO_PORT
    volumes:
      - ./data/matomo/app:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./docker/matomo/matomo.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/matomo/global.ini:/var/www/html/config/global.ini.php:ro
    ports:
      - ${MATOMO_PORT:-7003}:80
