#!/bin/bash

SCRIPTS=$(dirname "$0")
ROOT=$(realpath $SCRIPTS/..)

source $SCRIPTS/lib/config
source $SCRIPTS/lib/make-dockerignore
source $SCRIPTS/lib/custom-commands

make-dockerignore sapper

COMMON="-f docker-compose.yml -f docker-compose.dev.yml"
NODE="-f docker/node/docker-compose.yml -f docker/node/docker-compose.dev.yml"
HASURA="-f docker/hasura/docker-compose.yml -f docker/hasura/docker-compose.dev.yml"
POSTGRES="-f docker/postgres/docker-compose.yml -f docker/postgres/docker-compose.dev.yml"
MATOMO="-f docker/matomo/docker-compose.yml -f docker/matomo/docker-compose.dev.yml"
ADMIN="-f docker/react-admin/docker-compose.yml -f docker/react-admin/docker-compose.dev.yml"
SAPPER="-f docker/sapper/docker-compose.yml -f docker/sapper/docker-compose.dev.yml"
MATTERMOST="-f docker/mattermost/docker-compose.yml -f docker/mattermost/docker-compose.dev.yml"
FUSIONAUTH="-f docker/fusionauth/docker-compose.yml -f docker/fusionauth/docker-compose.dev.yml"
NGINX="-f docker/nginx/docker-compose.yml -f docker/nginx/docker-compose.dev.yml"

handle-custom-commands "$@"

docker-compose $COMMON $NGINX $NODE $POSTGRES $HASURA $MATOMO $ADMIN $SAPPER $FUSIONAUTH $MATTERMOST "$@"
