#!/bin/bash

SCRIPTS=$(dirname "$0")
ROOT=$(realpath $SCRIPTS/..)

source $SCRIPTS/lib/config
source $SCRIPTS/lib/make-dockerignore
source $SCRIPTS/lib/custom-commands

make-dockerignore frontend
make-dockerignore backend

COMMON="-f docker-compose.yml -f docker-compose.dev.yml"
FRONTEND="-f docker/frontend/docker-compose.yml -f docker/frontend/docker-compose.dev.yml"
BACKEND="-f docker/backend/docker-compose.yml -f docker/backend/docker-compose.dev.yml"
POSTGRES="-f docker/postgres/docker-compose.yml -f docker/postgres/docker-compose.dev.yml"
ADMIN="-f docker/react-admin/docker-compose.yml -f docker/react-admin/docker-compose.dev.yml"
# NGINX="-f docker/nginx/docker-compose.yml -f docker/nginx/docker-compose.dev.yml"

handle-custom-commands "$@"

# docker-compose $COMMON $NGINX $$FRONTEND $POSTGRES $HASURA $ADMIN "$@"
docker-compose $COMMON $NGINX $FRONTEND $BACKEND $POSTGRES $ADMIN "$@"
