#!/bin/bash

SCRIPTS=$(dirname "$0")
ROOT=$(realpath $SCRIPTS/..)

source $SCRIPTS/lib/config
source $SCRIPTS/lib/make-dockerignore
source $SCRIPTS/lib/custom-commands

make-dockerignore frontend
make-dockerignore backend

COMMON="-f docker-compose.yml -f docker-compose.dev.yml"
FRONTEND="-f docker/frontend/docker-compose.yml"
BACKEND="-f docker/backend/docker-compose.yml"
POSTGRES="-f docker/postgres/docker-compose.yml"
ADMIN="-f docker/react-admin/docker-compose.yml"
# NGINX="-f docker/nginx/docker-compose.yml -f docker/nginx/docker-compose.dev.yml"

FEATURES="-f docker/_features/static-sapper/docker-compose.yml"

handle-custom-commands "$@"

docker-compose $COMMON $NGINX $FRONTEND $BACKEND $POSTGRES $ADMIN "$@"

