#!/bin/bash

SCRIPTS=$(dirname "$0")
source $SCRIPTS/lib/config

COMMON="-f docker-compose.yml"
NODE="-f docker/node/docker-compose.yml"
HASURA="-f docker/hasura/docker-compose.yml"
POSTGRES="-f docker/postgres/docker-compose.yml"
MATOMO="-f matomo/postgres/docker-compose.yml"

docker-compose $COMMON $NODE $POSTGRES $HASURA $MATOMO "$@"